DROP DATABASE IF EXISTS anydea;
CREATE DATABASE anydea;
USE anydea;

CREATE TABLE user (
    PersonID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(8) NOT NULL
);

CREATE TABLE posts (
    PostID INT AUTO_INCREMENT PRIMARY KEY,
    PersonID INT,
    titulo VARCHAR(255) NOT NULL,
    conteudo TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PersonID) REFERENCES user(PersonID) 
);